name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Style checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - uses: actions/checkout@v4

      - name: Check clang-format
        run: |
          sudo apt-get -y install clang-format
          clang-format --dry-run --Werror simplefem/*

      - run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX:PATH=. ..
          make
          make install
        name: Install simplefem++

      - run: |
          export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:$(pwd)/build/lib/cmake"
          python test/run_tests.py
        name: Run unit tests
